// Hono type environment shared by all routes/middleware.
// `Env` (bindings) is generated by `pnpm cf-typegen` into worker-configuration.d.ts.
export interface AppEnv {
  Bindings: Env;
  Variables: {
    userEmail: string;
  };
}
