// Hono type environment shared by all routes/middleware.
// `Env` (bindings) is generated by `pnpm cf-typegen` into worker-configuration.d.ts.
// ENVIRONMENT is widened to string on purpose: the auth middleware treats any
// unrecognized value as production (fail closed), so the type must not pretend
// the value is always one of the configured literals.
export type Bindings = Omit<Env, "ENVIRONMENT"> & { ENVIRONMENT: string };

export interface AppEnv {
  Bindings: Bindings;
  Variables: {
    userEmail: string;
  };
}
